services:
  yacht:
    container_name: yacht
    image: selfhostedpro/yacht    
    restart: unless-stopped
    ports:
      - "${PORT}:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA}/config:/config

# volumes:
#  yacht:
