pages:
  - name: My Home
    columns:
      - size: full
        widgets:           
        - type: videos
          style: grid-cards
          collapse-after-rows: 2
          channels:
            - UCylGUf9BvQooEFjgdNudoQg
            - UCo71RUe6DX4w-Vd47rFLXPg
            - UCZNhwA1B5YqiY1nLzmM0ZRg            

        - type: group
          define: &card-properties
              type: reddit
              limit: 5
              collapse-after: 5
              style: horizontal-cards              
          widgets:
            - type: reddit
              subreddit: selfhosted
              collapse-after: 5
              show-flairs: true

            - subreddit: unixporn
              <<: *card-properties
              
            - subreddit: wallpapers
              <<: *card-properties

            - type: reddit         
              subreddit: freebsd
              collapse-after: 5
              show-flairs: true
              
            - type: reddit         
              subreddit: ObsidianMD
              collapse-after: 5
              show-flairs: true              
           
      - size: small
        widgets:
          - type: weather
            location: Puerto Colombia, Colombia

  - name: News
    columns:
      - size: full
        widgets:
          - type: rss
            title: techradar
            style: horizontal-cards
            feeds:
              - url: https://www.techradar.com/feeds.xml

          - type: rss
            title: gizmodo
            style: horizontal-cards
            feeds:
              - url: https://gizmodo.com/feed

          - type: rss
            title: computerworld
            style: horizontal-cards
            feeds:
              - url: https://www.computerworld.com/feed/

          - type: rss
            title: mit technology review
            style: horizontal-cards
            feeds:
              - url: https://www.technologyreview.com/feed/
                
      - size: small
        widgets:
          - type: rss
            title: zdnet - latest news
            style: vertical-cards
            collapse-after: 3
            feeds:
              - url: https://www.zdnet.com/news/rss.xml
                title: latest news

          - type: rss
            title: zdnet - linux
            style: vertical-cards
            collapse-after: 3
            feeds:
              - url: https://www.zdnet.com/topic/linux/rss.xml
                title: linux

          - type: rss
            title: zdnet - open source
            style: vertical-cards
            collapse-after: 3
            feeds:
              - url: https://www.zdnet.com/topic/open-source/rss.xml
                title: open source         
                             
  - name: Home
    columns:
      - size: small
        widgets:
          - type: calendar

          - type: rss
            limit: 10
            collapse-after: 3
            cache: 3h
            feeds:
              - url: https://ciechanow.ski/atom.xml
              - url: https://www.joshwcomeau.com/rss.xml
                title: Josh Comeau
              - url: https://samwho.dev/rss.xml
              - url: https://awesomekling.github.io/feed.xml
              - url: https://ishadeed.com/feed.xml
                title: Ahmad Shadeed

          - type: twitch-channels
            channels:
              - theprimeagen
              - cohhcarnage
              - christitustech
              - blurbs
              - asmongold
              - jembawls

      - size: full
        widgets:
          - type: hacker-news

          - type: videos
            channels:
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
              - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim

          - type: reddit
            subreddit: selfhosted

      - size: small
        widgets:
          - type: weather
            location: London, United Kingdom

          - type: markets
            markets:
              - symbol: SPY
                name: S&P 500
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: NVDA
                name: NVIDIA
              - symbol: AAPL
                name: Apple
              - symbol: MSFT
                name: Microsoft
              - symbol: GOOGL
                name: Google
              - symbol: AMD
                name: AMD
              - symbol: RDDT
                name: Reddit
