services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    volumes:
      - ${APP_DATA}/data:/app/data
    ports:
      - '${PORT}:3001'
